### ISSUE TITLE
soft link not working

### ISSUE THREAD

**Issue by EdoDImp** [PabloEnmanuelRamos/BioBlender21#1]
Hi,
I just tried to install Blender 2.82a on my Mac (OSX 10.15.13) and add Bioblender however, when I try to soft link 

imprima@mymac  ~/BioBlender $ > `ln -s ~/BioBlender ~/.config/blender/%BLENDER_VERSION_NUM%/scripts/addons/BioBlender`

it doesn't won't work

ln: /Users/imprima/.config/blender/%BLENDER_VERSION_NUM%/scripts/addons/BioBlender: No such file or directory

The .config file in my home directory is empty. Could you please help me with this?

Many thanks in advance,

Edoardo

**Comment by MonZop** [comment]
Hi Edo!,
the most likely explanation is that BioBlender is updated to Blender version 2.79. 
We are working on the new version, but we are not yet there!
