### ISSUE TITLE
Keyframes for atoms

### ISSUE THREAD

**Issue by MonZop** [PabloEnmanuelRamos/BioBlender21#10]
When >1 Models are imported,  Bioblender set keyframes for Location, Rotation, and Scale for each atom: it should be Location only, because the rotation and scale must never change (except for specific operations set by the user).

**Comment by PabloEnmanuelRamos** [comment]
Hi Monica, 
The problem has already been solved. Bioblender now only sets keyframes for Location. 
Regards
