### ISSUE TITLE
EP calculation in Linux

### ISSUE THREAD

**Issue by tizeta** [PabloEnmanuelRamos/BioBlender21#11]
The EP calculation crashes in Linux.

**Comment by tizeta** [comment]
Version of BB 05 august

Import fails with error:

PDB String 1
Bootstrapping
Import Failed 1: 'NoneType' object has no attribute 'nodes'

**Comment by PabloEnmanuelRamos** [comment]
It is now possible to calculate the EP on Linux.  Errors of SCIVIS binary were corrected, it is now available for 32 Bits and 64 Bits architecture.  To calculate the electrostatic equations, the APBS software is called.  
The following lines of code are required for its installation:
sudo apt update
sudo apt install apbs
