### ISSUE TITLE
Unable to import a 2IF1

### ISSUE THREAD

**Issue by daenbol** [PabloEnmanuelRamos/BioBlender21#7]
It just stuck after clicking Import PDB. I tried to import both with file or by ID but it just stays in a not responding state forever. After a whole night of importing it keep being stacked.

**Comment by PabloEnmanuelRamos** [comment]
Hello Daenbol,
I just downloaded the PDB 2IF1, and the BioBlender worked perfectly for me, in just a few seconds it imported all the atoms. However I downloaded the BioBlender from Github and tried again and it worked for me.
Have you tried some other PDB and the same thing happens to you?
If you could open the Blender from the Windows console it would be much better to know if it gives you an error during the import of the PDB.
Any mistake or doubt let me know.
Regards.
