### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by BradyAJohnston** [PabloEnmanuelRamos/BioBlender21#8]
Is there any kind of documentation / tutorial on how to use this? I have managed to install it, load a PDB file and generate surface meshes - but I am unable to generate any kind of field lines. When trying to render them the program thinks / freezes for a bit and generates a new surface mesh, but nothing else appears in the scene. Are there other requirements that need to be installed to enable the different fields? 

Thanks for updating this to 2.93!

**Comment by MonZop** [comment]
Hi Brady! Thanks for testing. It works in our hands. It may take a while to generate the EP, for which it uses APBS. The procedure is (after loading the molecule):
go to the EP Visualization. For faster calculation, increase the grid spacing to 2, then click Show EP.
(For the EP, it should not generate a new surface, but only a new object called Empy_Lines, visible in the Outliner).
![image](https://user-images.githubusercontent.com/10231334/125424836-52e54acc-00c3-4d6d-9dc8-bee08e5f5c79.png)

It also generates the lines, and automatically start the animation. 
After this you can start rendering.
If you want to send your PDB, I can see if I identify any specific problems.
Also, if you start Blender from the console, there might be some indication of what went wrong.

**Comment by tizeta** [comment]
Hi Brady, thanks for testing BioBlender.
Right now, two things come to my mind, they are both bugs that we are working on.
The first one is relevant to Linux, not sure what OS you are using, but the EP calculation is broken on Linux.
The other ones has to do with selection. To get the EP working in Windows you need to have selected the empty object that is named after the molecule that you want to process. In the picture shared by Monica, for example, that would be 1cfc.001 
You can use the outliner (the empty is hidden in the 3D view but visible and selectable in the outliner).

**Comment by MonZop** [comment]
> To get the EP working in Windows you need to have selected the empty object

I'm not sure about this: EP is a calculated scene wide, in order to include the potentials generated by all molecules in the scene, and possibly reveal their interaction. Threre's no need to select a specific protein, and if one is selected, the selection should be ignored.

**Comment by BradyAJohnston** [comment]
Hi all, 
Thanks for the information, I appreciate the quick responses.  For context I'm working on Windows10.

I tried selecting the empty and pressing "show EP" but I was still getting the same result. There was no obvious error message, and I was getting 2x meshes generated each time that I clicked the "show EP" button. 

Looking at console when - it turns out BioBlender was looking for a system-installation of python that wasn't there to do the calcs. Seems that when that failed it just returned 2x meshes instead? 

Thankfully though - with a proper system installation of python (3.8 from the Windows Store) it now works fine and generates and animates the field lines.

Thanks for making the addon! I have been awaiting the BioBlender 2.1 release for quite some time - eager to play around with it inside of Blender 2.8+. I will see how I go making some stuff, and then I will be sure to make a video about it on my channel (https://youtu.be/FfXJsvxhRQk).

Cheers!

**Comment by tizeta** [comment]
Hi Brady, thanks for taking the time to test BioBlender! 
I was watching one of your tutorials and I must say it's really, really well done. 
I'm looking forward to seeing the one about BB, it will be very helpful to the community. 
Cheers! 
Tiziana
